.ONESHELL:
default: help
PHONY: install check test setup-env install-pre-commit-hook bootstrap clean bumpversion help
SHELL = bash
ENVIRONMENT ?= dev
NAME ?= resume
TRASH_DIRS ?= build dist *.egg-info .tox .mypy_cache .pytest_cache __pycache__ htmlcov
TRASH_FILES ?= .coverage
VERSION ?= `python -c "import configparser; config = configparser.ConfigParser(); config.read('setup.cfg'); print(config['metadata']['version']);"`


install:
	ENVIRONMENT="{$(ENVIRONMENT) | tr -d \'[:blank:]\'}";\
	if [[ "${ENVIRONMENT}" ]]; then
		python -m pip install .[$(ENVIRONMENT)];\
	else
		python -m pip install .;\
	fi

check:
	bash -c 'pre-commit run --all-files';\

test:
	PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$${PYTHONPATH}:$${PWD}" pytest --import-mode=importlib --cov=$(NAME) $(TESTS);\

setup-env:
	cp .env.example .env;\
	direnv allow;\

install-pre-commit-hook:
	pre-commit install;\

bootstrap: setup-env install install-pre-commit-hook

shell:
	PYTHONPATH="$${PYTHONPATH}:$${PWD}" bpython;\

clean:
	for file in $(TRASH_FILES); do\
		find -iname $${file} -print0 | xargs -0 rm -rf;\
	done;\
	for dir in $(TRASH_DIRS); do\
		find -type d -name $${dir} ! -path "*/.direnv/*" -print0 | xargs -0 rm -rf;\
	done;\

bumpversion:
	git tag -a $(VERSION) -m "v$(VERSION)";\

help:
	@echo "    help:"
	@echo "        Show this help."
	@echo "    install:"
	@echo "        Install requirements."
	@echo "    check:"
	@echo "        Perform some code checks."
	@echo "    test:"
	@echo "        Run tests, can specify tests with 'TESTS' variable."
	@echo "    setup-env:"
	@echo "        Copy example environment config for development and setup virtualenv."
	@echo "    install-pre-commit-hook:"
	@echo "        Setup pre commit hook."
	@echo "    bootstrap:"
	@echo "        Bootstrap project."
	@echo "    shell:"
	@echo "        Open python REPL with loaded application."
	@echo "    clean:"
	@echo "        Recursively delete useless autogenerated files and directories, directories and files lists can be overriden through 'TRASH_DIRS' and 'TRASH_FILES' variables."
	@echo "    bumpversion:"
	@echo "        Tag current code revision with version."
