name: "build"
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  DEFAULT_PYTHON_VERSION: "3.13"
  DEFAULT_NODE_VERSION: "22.14"
  DEFAULT_UV_VERSION: "0.6.12"
jobs:
  check:
    uses: "./.github/workflows/check.yml"
  test:
    uses: "./.github/workflows/test.yml"
    needs: ["check"]
  check-requirements:
    uses: "./.github/workflows/check-requirements.yml"
