name: "build"
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      python-version:
        type: "string"
        required: false
        description: "Python version"
        default: "3.13"
      node-version:
        type: "string"
        required: false
        description: "Node.js version"
        default: "22.14"
      uv-version:
        type: "string"
        required: false
        description: "uv version"
        default: "0.6.16"
      ubuntu-version:
        type: "string"
        required: false
        description: "Ubuntu version"
        default: "ubuntu-24.04"
  workflow_call:
    inputs:
      python-version:
        type: "string"
        required: false
        description: "Python version"
        default: "3.13"
      node-version:
        type: "string"
        required: false
        description: "Node.js version"
        default: "22.14"
      uv-version:
        type: "string"
        required: false
        description: "uv version"
        default: "0.6.16"
      ubuntu-version:
        type: "string"
        required: false
        description: "Ubuntu version"
        default: "ubuntu-24.04"
jobs:
  check:
    uses: "./.github/workflows/check.yml"
  test:
    uses: "./.github/workflows/test.yml"
    if: "success()"
    needs:
      - "check"
  check-requirements:
    uses: "./.github/workflows/check-requirements.yml"
