name: "check"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  DEFAULT_PYTHON_VERSION: "3.11"
  DEFAULT_NODE_VERSION: "20.3"
jobs:
  check:
    name: "check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v3.5.3"
      - name: "Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v4.7.0"
        with:
          python-version: "${{ env.DEFAULT_PYTHON_VERSION }}"
      - name: "Set up Node.js ${{ env.DEFAULT_NODE_VERSION }}"
        id: "set-up-node"
        uses: "actions/setup-node@v3.8.1"
        with:
          node-version: "${{ env.DEFAULT_NODE_VERSION }}"
      - name: "Pip cache"
        id: "pip-cache"
        uses: "actions/cache@v3.3.1"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-pip-"
      - name: "Npm cache"
        id: "npm-cache"
        uses: "actions/cache@v3.3.1"
        with:
          path: "~/.npm"
          key: "${{ runner.os }}-npm-${{ hashFiles('package.json') }}"
          restore-keys: |
            "${{ runner.os }}-npm-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Install JavaScript requirements"
        id: "install-js-requirements"
        run: "npm install"
      - name: "Perform code checks"
        id: "perform-code-check"
        run: "make check"
