name: "check"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  DEFAULT_PYTHON_VERSION: "3.13"
  DEFAULT_NODE_VERSION: "22.14"
  DEFAULT_UV_VERSION: "0.6.12"
jobs:
  check:
    name: "check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v5.1.1"
        with:
          python-version: "${{ env.DEFAULT_PYTHON_VERSION }}"
      - name: "Set up Node.js ${{ env.DEFAULT_NODE_VERSION }}"
        id: "set-up-node"
        uses: "actions/setup-node@v4.0.3"
        with:
          node-version: "${{ env.DEFAULT_NODE_VERSION }}"
      - name: "Set up uv"
        id: "set-up-uv"
        uses: "astral-sh/setup-uv@v5.4.1"
        with:
          version: "${{ env.DEFAULT_UV_VERSION }}"
      - name: "uv cache"
        id: "uv-cache"
        uses: "actions/cache@v4.2.3"
        with:
          path: "~/.cache/uv"
          key: "${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-uv-"
      - name: "npm cache"
        id: "npm-cache"
        uses: "actions/cache@v4.2.3"
        with:
          path: "~/.npm"
          key: "${{ runner.os }}-npm-${{ hashFiles('package.json') }}"
          restore-keys: |
            "${{ runner.os }}-npm-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Install JavaScript requirements"
        id: "install-js-requirements"
        run: "make install-js-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Perform code checks"
        id: "perform-code-checks"
        run: "make check"
