name: "check"
on:
  workflow_dispatch:
    inputs:
      python-version:
        type: "string"
        required: false
        description: "Python version"
        default: "3.13"
      node-version:
        type: "string"
        required: false
        description: "Node.js version"
        default: "22.14"
      uv-version:
        type: "string"
        required: false
        description: "uv version"
        default: "0.6.12"
      ubuntu-version:
        type: "string"
        required: false
        description: "Ubuntu version"
        default: "ubuntu-24.04"
  workflow_call:
    inputs:
      python-version:
        type: "string"
        required: false
        description: "Python version"
        default: "3.13"
      node-version:
        type: "string"
        required: false
        description: "Node.js version"
        default: "22.14"
      uv-version:
        type: "string"
        required: false
        description: "uv version"
        default: "0.6.12"
      ubuntu-version:
        type: "string"
        required: false
        description: "Ubuntu version"
        default: "ubuntu-24.04"
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  VIRTUAL_ENV: "~/.venv"
jobs:
  check:
    name: "check"
    runs-on: "${{ inputs.ubuntu-version }}"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up Python ${{ inputs.python-version }}"
        id: "set-up-python"
        uses: "actions/setup-python@v5.5.0"
        with:
          python-version: "${{ inputs.python-version }}"
      - name: "Set up Node.js ${{ inputs.node-version }}"
        id: "set-up-node"
        uses: "actions/setup-node@v4.3.0"
        with:
          node-version: "${{ inputs.node-version }}"
      - name: "Set up uv ${{ inputs.uv-version }}"
        id: "set-up-uv"
        uses: "astral-sh/setup-uv@v5.4.1"
        with:
          version: "${{ inputs.uv-version }}"
      - name: "Configuring uv cache"
        id: "configure-uv-cache"
        uses: "actions/cache@v4.2.3"
        with:
          path: "~/.cache/uv"
          key: "${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-uv-"
      - name: "Configuring npm cache"
        id: "configure-npm-cache"
        uses: "actions/cache@v4.2.3"
        with:
          path: "~/.npm"
          key: "${{ runner.os }}-npm-${{ hashFiles('package.json') }}"
          restore-keys: |
            "${{ runner.os }}-npm-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Install JavaScript requirements"
        id: "install-js-requirements"
        run: "make install-js-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Perform code checks"
        id: "perform-code-checks"
        run: "make check"
