name: "test"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  PYTHON_VERSION: "3.13"
  UV_VERSION: "0.6.12"
  UBUNTU_VERSION: "ubuntu-24.04"
jobs:
  test:
    name: "test"
    runs-on: "${{ env.UBUNTU_VERSION }}"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up Python ${{ env.PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v5.5.0"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: "Set up uv"
        id: "set-up-uv"
        uses: "astral-sh/setup-uv@v5.4.1"
        with:
          version: "${{ env.UV_VERSION }}"
      - name: "Configuring uv cache"
        id: "configure-uv-cache"
        uses: "actions/cache@v4.2.3"
        with:
          path: "~/.cache/uv"
          key: "${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-uv-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Run tests"
        id: "run-tests"
        run: "make test"
