name: "test"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  DEFAULT_PYTHON_VERSION: "3.13"
  DEFAULT_UV_VERSION: "0.6.12"
jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v5.1.1"
        with:
          python-version: "${{ env.DEFAULT_PYTHON_VERSION }}"
      - name: "Set up uv"
        id: "set-up-uv"
        uses: "astral-sh/setup-uv@v5.4.1"
        with:
          version: "${{ env.DEFAULT_UV_VERSION }}"
      - name: "uv cache"
        id: "uv-cache"
        uses: "actions/cache@v4.0.2"
        with:
          path: "~/.cache/uv"
          key: "${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-uv-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Run tests"
        id: "run-tests"
        run: "make test"
