name: "test"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "resume"
  ENVIRONMENT: "dev"
  DEFAULT_PYTHON_VERSION: "3.12"
jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v4.1.1"
      - name: "Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v4.7.1"
        with:
          python-version: "${{ env.DEFAULT_PYTHON_VERSION }}"
      - name: "Pip cache"
        id: "pip-cache"
        uses: "actions/cache@v4.0.2"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}"
          restore-keys: |
            "${{ runner.os }}-pip-"
      - name: "Install Python requirements"
        id: "install-python-requirements"
        run: "make install-python-requirements ENVIRONMENT=${{ env.ENVIRONMENT }}"
      - name: "Run tests"
        id: "run-tests"
        run: "make test"
